In [3]:
import numpy as np
import pandas as pd

In [4]:
data = {
    'Zone': ['Central', 'North', 'South', 'East', 'West'] * 3,
    'Time': ['Morning'] * 5 + ['Evening'] * 5 + ['Night'] * 5,
    'Vehicles': [900, 500, 450, 650, 400,
                 1100, 700, 600, 800, 550,
                 300, 200, 180, 250, 150],
    'Speed': [20, 35, 40, 30, 45,
              12, 25, 32, 18, 38,
              45, 55, 58, 50, 60],
    'PM25': [80, 40, 30, 55, 25,
             100, 60, 45, 75, 35,
             25, 18, 15, 20, 12]
}

df = pd.DataFrame(data)
df

       Zone     Time  Vehicles  Speed  PM25
0   Central  Morning       900     20    80
1     North  Morning       500     35    40
2     South  Morning       450     40    30
3      East  Morning       650     30    55
4      West  Morning       400     45    25
5   Central  Evening      1100     12   100
6     North  Evening       700     25    60
7     South  Evening       600     32    45
8      East  Evening       800     18    75
9      West  Evening       550     38    35
10  Central    Night       300     45    25
11    North    Night       200     55    18
12    South    Night       180     58    15
13     East    Night       250     50    20
14     West    Night       150     60    12

In [5]:
df.head()

      Zone     Time  Vehicles  Speed  PM25
0  Central  Morning       900     20    80
1    North  Morning       500     35    40
2    South  Morning       450     40    30
3     East  Morning       650     30    55
4     West  Morning       400     45    25

In [6]:
df.head(3)

      Zone     Time  Vehicles  Speed  PM25
0  Central  Morning       900     20    80
1    North  Morning       500     35    40
2    South  Morning       450     40    30

In [7]:
df.tail()

       Zone   Time  Vehicles  Speed  PM25
10  Central  Night       300     45    25
11    North  Night       200     55    18
12    South  Night       180     58    15
13     East  Night       250     50    20
14     West  Night       150     60    12

In [8]:
df.tail(4)

     Zone   Time  Vehicles  Speed  PM25
11  North  Night       200     55    18
12  South  Night       180     58    15
13   East  Night       250     50    20
14   West  Night       150     60    12

In [9]:
df.shape

(15, 5)

In [10]:
df.columns

Index(['Zone', 'Time', 'Vehicles', 'Speed', 'PM25'], dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Zone      15 non-null     object
 1   Time      15 non-null     object
 2   Vehicles  15 non-null     int64
 3   Speed     15 non-null     int64
 4   PM25      15 non-null     int64
dtypes: int64(3), object(2)
memory usage: 732.0+ bytes

In [12]:
df.describe()

          Vehicles      Speed        PM25
count    15.000000  15.000000   15.000000
mean    515.333333  37.533333   42.333333
std     281.751326  14.865428   26.540176
min     150.000000  12.000000   12.000000
25%     275.000000  27.500000   22.500000
50%     500.000000  38.000000   35.000000
75%     675.000000  47.500000   57.500000
max    1100.000000  60.000000  100.000000

In [13]:
df.isnull().sum()

Zone        0
Time        0
Vehicles    0
Speed       0
PM25        0
dtype: int64

In [14]:
df.duplicated().sum()

0

In [15]:
vehicles_arr = np.array(df['Vehicles'])
pm25_arr = np.array(df['PM25'])

avg_vehicles = np.mean(vehicles_arr)
min_vehicles = np.min(vehicles_arr)
max_vehicles = np.max(vehicles_arr)
total_vehicles = np.sum(vehicles_arr)

print("Average:", avg_vehicles)
print("Minimum:", min_vehicles)
print("Maximum:", max_vehicles)
print("Total:", total_vehicles)

Average: 515.3333333333334
Minimum: 150
Maximum: 1100
Total: 7730

In [16]:
df['Vehicles_in_Hundreds'] = df['Vehicles'] / 100
df['Speed_mps'] = df['Speed'] / 3.6
df['PM25_per_Vehicle'] = df['PM25'] / df['Vehicles']

df.head()

,Zone,Time,Vehicles,Speed,PM25,Vehicles_in_Hundreds,Speed_mps,PM25_per_Vehicle
0,Central,Morning,900,20,80,9.0,5.555556,0.088889
1,North,Morning,500,35,40,5.0,9.722222,0.080000
2,South,Morning,450,40,30,4.5,11.111111,0.066667
3,East,Morning,650,30,55,6.5,8.333333,0.084615
4,West,Morning,400,45,25,4.0,12.500000,0.062500

In [17]:
# Average, minimum, maximum and total
df['Vehicles'].mean()

515.3333333333334

In [18]:
df['Vehicles'].min()

150

In [19]:
df['Vehicles'].max()

1100

In [20]:
df['Vehicles'].sum()

7730

In [21]:
# High pollution observations
high_pollution = df[df['PM25'] > 50]
high_pollution

,Zone,Time,Vehicles,Speed,PM25,Vehicles_in_Hundreds,Speed_mps,PM25_per_Vehicle
0,Central,Morning,900,20,80,9.0,5.555556,0.088889
3,East,Morning,650,30,55,6.5,8.333333,0.084615
5,Central,Evening,1100,12,100,11.0,3.333333,0.090909
6,North,Evening,700,25,60,7.0,6.944444,0.085714
8,East,Evening,800,18,75,8.0,5.000000,0.093750

In [22]:
# High traffic and low speed
congestion = df[(df['Vehicles'] > 600) & (df['Speed'] < 25)]
congestion

,Zone,Time,Vehicles,Speed,PM25,Vehicles_in_Hundreds,Speed_mps,PM25_per_Vehicle
0,Central,Morning,900,20,80,9.0,5.555556,0.088889
5,Central,Evening,1100,12,100,11.0,3.333333,0.090909
8,East,Evening,800,18,75,8.0,5.000000,0.093750

In [23]:
# Sort by pollution, highest first
df.sort_values(by='PM25', ascending=False)

,Zone,Time,Vehicles,Speed,PM25,Vehicles_in_Hundreds,Speed_mps,PM25_per_Vehicle
5,Central,Evening,1100,12,100,11.0,3.333333,0.090909
0,Central,Morning,900,20,80,9.0,5.555556,0.088889
8,East,Evening,800,18,75,8.0,5.000000,0.093750
6,North,Evening,700,25,60,7.0,6.944444,0.085714
3,East,Morning,650,30,55,6.5,8.333333,0.084615
7,South,Evening,600,32,45,6.0,8.888889,0.075000
1,North,Morning,500,35,40,5.0,9.722222,0.080000
9,West,Evening,550,38,35,5.5,10.555556,0.063636
2,South,Morning,450,40,30,4.5,11.111111,0.066667
4,West,Morning,400,45,25,4.0,12.500000,0.062500
10,Central,Night,300,45,25,3.0,12.500000,0.083333
13,East,Night,250,50,20,2.5,13.888889,0.080000
11,North,Night,200,55,18,2.0,15.277778,0.090000
12,South,Night,180,58,15,1.8,16.111111,0.083333
14,West,Night,150,60,12,1.5,16.666667,0.080000

In [24]:
df.groupby('Time')[['Vehicles', 'Speed', 'PM25']].mean()

         Vehicles  Speed  PM25
Time
Evening     750.0   25.0  63.0
Morning     580.0   34.0  46.0
Night       216.0   53.6  18.0

In [25]:
correlation = df[['Vehicles', 'Speed', 'PM25']].corr()
correlation

          Vehicles     Speed      PM25
Vehicles  1.000000 -0.980485  0.982568
Speed    -0.980485  1.000000 -0.965643
PM25      0.982568 -0.965643  1.000000

In [26]:
df['Predicted_PM25'] = df.groupby('Time')['PM25'].transform('mean')
df[['Zone', 'Time', 'PM25', 'Predicted_PM25']]

       Zone     Time  PM25  Predicted_PM25
0   Central  Morning    80            46.0
1     North  Morning    40            46.0
2     South  Morning    30            46.0
3      East  Morning    55            46.0
4      West  Morning    25            46.0
5   Central  Evening   100            63.0
6     North  Evening    60            63.0
7     South  Evening    45            63.0
8      East  Evening    75            63.0
9      West  Evening    35            63.0
10  Central    Night    25            18.0
11    North    Night    18            18.0
12    South    Night    15            18.0
13     East    Night    20            18.0
14     West    Night    12            18.0

In [27]:
df['Action'] = np.where(
    (df['Vehicles'] > 600) & (df['Speed'] < 25),
    'Investigate congestion',
    'Continue monitoring'
)

df[['Zone', 'Time', 'Vehicles', 'Speed', 'Action']]

       Zone     Time  Vehicles  Speed                  Action
0   Central  Morning       900     20  Investigate congestion
1     North  Morning       500     35     Continue monitoring
2     South  Morning       450     40     Continue monitoring
3      East  Morning       650     30     Continue monitoring
4      West  Morning       400     45     Continue monitoring
5   Central  Evening      1100     12  Investigate congestion
6     North  Evening       700     25     Continue monitoring
7     South  Evening       600     32     Continue monitoring
8      East  Evening       800     18  Investigate congestion
9      West  Evening       550     38     Continue monitoring
10  Central    Night       300     45     Continue monitoring
11    North    Night       200     55     Continue monitoring
12    South    Night       180     58     Continue monitoring
13     East    Night       250     50     Continue monitoring
14     West    Night       150     60     Continue monitoring